version: '3'
services:
  flask:
    build: .
    command: gunicorn -b 0.0.0.0:5001 main:app --reload --timeout 1200
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=True
    ports:
      - "5001:5001"
    volumes:
      - ./:/root